#cloud-config
package_update: true
package_upgrade: false

packages:
  - mysql-server
  - redis-server
  - git
  - python3
  - python3-pip
  - python3-venv
  - nginx
  - openssl

write_files:
  - path: /etc/systemd/system/app.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Gunicorn service for Flask simpleForum
      After=network.target mysql.service redis-server.service

      [Service]
      Restart=always
      RestartSec=5
      User=ubuntu
      Group=www-data
      WorkingDirectory=/home/ubuntu/simpleForum
      Environment="PATH=/home/ubuntu/simpleForum/venv/bin"
      ExecStart=/home/ubuntu/simpleForum/venv/bin/gunicorn \
          --workers 3 \
          --bind unix:/home/ubuntu/simpleForum/gunicorn.sock \
          --access-logfile /home/ubuntu/simpleForum/logs/access.log \
          --error-logfile /home/ubuntu/simpleForum/logs/error.log \
          wsgi:app

      [Install]
      WantedBy=multi-user.target

runcmd:
  # ===== 1. Environment variables =====
  - SQL_USER="flaskuser"
  - SQL_PASS="flaskpass"
  - ROOT_SQL_PASS="rootpass"
  - REDIS_USER="flaskuser"
  - REDIS_PASS="flaskpass"
  - SECRET_KEY="EnterYourSecretKeyHere"

  - DATABASE_URL="mysql+pymysql://$SQL_USER:$SQL_PASS@127.0.0.1/flaskdb?charset=utf8mb4"
  - REDIS_URL="redis://$REDIS_USER:$REDIS_PASS@127.0.0.1:6379/0"

  # ===== 2. Wait for MySQL ready =====
  - until systemctl is-active --quiet mysql; do sleep 3; done

  # ===== 3. MySQL =====================
  - mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$ROOT_SQL_PASS'; FLUSH PRIVILEGES;"

  - |
    mysql -uroot -p$ROOT_SQL_PASS <<EOF
    CREATE DATABASE IF NOT EXISTS flaskdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '$SQL_USER'@'localhost' IDENTIFIED BY '$SQL_PASS';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES ON flaskdb.* TO '$SQL_USER'@'localhost';
    FLUSH PRIVILEGES;
    EOF

  # ===== 4. Redis ======================
  - redis-cli ACL SETUSER $REDIS_USER on "$REDIS_PASS" ~* +get +set +del +exists +expire +ttl
  - sed -i "s/^# requirepass .*/requirepass $REDIS_PASS/" /etc/redis/redis.conf
  - sed -i "s/^bind .*/bind 127.0.0.1/" /etc/redis/redis.conf
  - sed -i "s/^protected-mode no/protected-mode yes/" /etc/redis/redis.conf
  - systemctl enable redis-server
  - systemctl restart redis-server

  # ===== 5. Clone app ==================
  - git clone https://github.com/BlazJe/simpleForum.git /home/ubuntu/simpleForum
  - chown -R ubuntu:ubuntu /home/ubuntu/simpleForum

  # ===== 6. Create .env file ===========
  - |
    cat > /home/ubuntu/simpleForum/.env <<EOF
    SECRET_KEY="$SECRET_KEY"
    DATABASE_URL="$DATABASE_URL"
    REDIS_URL="$REDIS_URL"
    EOF

  # ===== 7. Python venv ================
  - cd /home/ubuntu/simpleForum
  - python3 -m venv venv
  - /home/ubuntu/simpleForum/venv/bin/pip install --upgrade pip
  - /home/ubuntu/simpleForum/venv/bin/pip install -r requirements.txt

  # ===== 8. Logging dirs ===============
  - mkdir -p /home/ubuntu/simpleForum/logs
  - chown -R ubuntu:www-data /home/ubuntu/simpleForum/logs
  - chmod 750 /home/ubuntu/simpleForum/logs

  # ===== 9. Permissions for Nginx/Gunicorn =====
  - chown -R ubuntu:www-data /home/ubuntu/simpleForum
  - chmod 711 /home/ubuntu
  - chmod 750 /home/ubuntu/simpleForum

  # ===== 10. Enable + start Gunicorn ===
  - systemctl daemon-reload
  - systemctl enable app.service
  - systemctl start app.service
  - sleep 3

  # Fix socket permissions after start
  - |
    if [ -S /home/ubuntu/simpleForum/gunicorn.sock ]; then
      chown ubuntu:www-data /home/ubuntu/simpleForum/gunicorn.sock
      chmod 660 /home/ubuntu/simpleForum/gunicorn.sock
    fi

  # ===== 11. SSL + Nginx config =========
  - mkdir -p /etc/nginx/ssl
  - openssl ecparam -genkey -name prime256v1 -out /etc/nginx/ssl/ecc.key
  - openssl req -new -x509 -key /etc/nginx/ssl/ecc.key -out /etc/nginx/ssl/ecc.crt -days 365 -subj "/CN=localhost"

  - |
    cat > /etc/nginx/sites-available/simpleforum.conf <<EOF
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/ssl/ecc.crt;
        ssl_certificate_key /etc/nginx/ssl/ecc.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ecdh_curve prime256v1;
        ssl_prefer_server_ciphers on;

        location / {
            include proxy_params;
            proxy_pass http://unix:/home/ubuntu/simpleForum/gunicorn.sock;
        }
    }
    EOF

  - ln -sf /etc/nginx/sites-available/simpleforum.conf /etc/nginx/sites-enabled/simpleforum.conf
  - rm -f /etc/nginx/sites-enabled/default
  - systemctl enable nginx
  - nginx -t
  - systemctl restart nginx
