#cloud-config
package_update: true
package_upgrade: true

packages:
  - mysql-server
  - redis-server
  - git
  - python3
  - python3-pip
  - python3-venv
  - nginx

users:
  - name: vagrant
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

write_files:
  - path: /etc/mysql/mysql.conf.d/custom.cnf
    content: |
      [mysqld]
      bind-address = 127.0.0.1

  - path: /home/vagrant/setup.sql
    content: |
      ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpass';
      FLUSH PRIVILEGES;
      CREATE DATABASE IF NOT EXISTS flaskdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
      CREATE USER IF NOT EXISTS 'flaskuser'@'localhost' IDENTIFIED BY 'flaskpass';
      GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES ON flaskdb.* TO 'flaskuser'@'localhost';
      FLUSH PRIVILEGES;

  - path: /etc/redis/redis.conf
    content: |
      bind 127.0.0.1
      protected-mode yes
      requirepass flaskpass123!
      port 6379

  - path: /home/vagrant/.env
    content: |
      SECRET_KEY=k9G3vPq2sR8xZtN4wL0uF6yH1aB7mC5dE2jK0oQ9rT3sV6zX8nY1pU4
      DATABASE_URL=mysql+pymysql://flaskuser:flaskpass@127.0.0.1/flaskdb?charset=utf8mb4
      REDIS_URL=redis://flaskuser:flaskpass123!@127.0.0.1:6379/0

  - path: /etc/systemd/system/app.service
    content: |
      [Unit]
      Description=Gunicorn service for Flask simpleForum
      After=network.target mysql.service redis-server.service

      [Service]
      Restart=always
      RestartSec=5
      User=vagrant
      Group=www-data
      WorkingDirectory=/home/vagrant/simpleForum
      Environment="PATH=/home/vagrant/simpleForum/venv/bin"
      ExecStart=/home/vagrant/simpleForum/venv/bin/gunicorn \
          --workers 3 \
          --bind unix:/home/vagrant/simpleForum/gunicorn.sock \
          --access-logfile /home/vagrant/simpleForum/logs/access.log \
          --error-logfile /home/vagrant/simpleForum/logs/error.log \
          wsgi:app

      [Install]
      WantedBy=multi-user.target

  - path: /etc/nginx/sites-available/simpleforum.conf
    content: |
      server {
          listen 443 ssl;
          server_name localhost;

          ssl_certificate /etc/nginx/ssl/ecc.crt;
          ssl_certificate_key /etc/nginx/ssl/ecc.key;
          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_ecdh_curve prime256v1;
          ssl_prefer_server_ciphers on;

          location / {
              include proxy_params;
              proxy_pass http://unix:/home/vagrant/simpleForum/gunicorn.sock;
          }
      }

runcmd:
  # Configura MySQL
  - mysql -u root < /home/vagrant/setup.sql
  - systemctl enable mysql
  - systemctl restart mysql

  # Configura Redis
  - redis-cli ACL SETUSER flaskuser on "flaskpass123!" ~* +get +set +del +exists +expire +ttl
  - systemctl enable redis-server
  - systemctl restart redis-server

  # Crea gruppo www-data e aggiungi utente
  - groupadd -f www-data
  - usermod -a -G www-data vagrant

  # Clona repository e setup Python
  - sudo -u vagrant git clone https://github.com/BlazJe/simpleForum.git /home/vagrant/simpleForum
  - cd /home/vagrant/simpleForum
  - sudo -u vagrant python3 -m venv venv
  - sudo -u vagrant /home/vagrant/simpleForum/venv/bin/pip install --upgrade pip
  - sudo -u vagrant /home/vagrant/simpleForum/venv/bin/pip install -r requirements.txt

  # Crea directory logs e imposta permessi
  - mkdir -p /home/vagrant/simpleForum/logs
  - chown -R vagrant:www-data /home/vagrant/simpleForum
  - chmod 711 /home/vagrant
  - chmod 750 /home/vagrant/simpleForum
  - chmod 750 /home/vagrant/simpleForum/logs

  # Setup SSL per Nginx
  - mkdir -p /etc/nginx/ssl
  - openssl ecparam -genkey -name prime256v1 -out /etc/nginx/ssl/ecc.key
  - openssl req -new -x509 -key /etc/nginx/ssl/ecc.key -out /etc/nginx/ssl/ecc.crt -days 365 -subj "/CN=localhost" -nodes
  - chmod 600 /etc/nginx/ssl/ecc.key

  # Configura Nginx
  - ln -sf /etc/nginx/sites-available/simpleforum.conf /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - systemctl enable nginx
  - systemctl restart nginx

  # Avvia l'applicazione
  - systemctl daemon-reload
  - systemctl enable app.service
  - systemctl start app.service

final_message: "Setup completato! L'applicazione è disponibile su HTTPS"